"https://{default}/":
    type: upstream
    upstream: "magerepository:php"

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"

"http://{default}/":
    type: redirect
    to: "https://{default}/"

"http://www.{default}/":
    type: redirect
    to: "https://{default}/"